# A sample app.yaml file--you can upload this to an
# alternate version of your application with appcfg.py -A yourapp
application: YOUR APPLICATION 
version: applywrites
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin


- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

